---

# Testing playbook.... use with VM

- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.138/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"
  tasks:
    - name: Add Command to Centreon
      centreon_command:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "App-DB-Redis-cli-clients"
        type: "check"
        line: |
          $CENTREONPLUGINS$/centreon_redis_cli.pl --plugin=apps::redis::cli::plugin --mode=clients --hostname=$HOSTADDRESS$ --port='$_HOSTREDISPORT$' --username='$_HOSTREDISUSERNAME$' --password='$_HOSTREDISPASSWORD$' --warning-connected-clients='$_SERVICEWARNINGCONNECTEDCLIENTS$' --critical-connected-clients='$_SERVICECRITICALCONNECTEDCLIENTS$' --warning-blocked-clients='$_SERVICEWARNINGBLOCKEDCLIENTS$' --critical-blocked-clients='$_SERVICECRITICALBLOCKEDCLIENTS$' --warning-client-longest-output-list='$_SERVICEWARNINGLONGESTOUTPUTLIST$' --critical-client-longest-output-list='$_SERVICECRITICALLONGESTOUTPUTLIST$' --warning-client-biggest-input-buf='$_SERVICEWARNINGBIGGESTINPUTBUFF$' --critical-client-biggest-input-buf='$_SERVICECRITICALBIGGESTINPUTBUFF$'
      delegate_to: localhost
      notify: "centreon api applycfg"
  tags:
    - command

- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.138/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"

  tasks:
    - name: Add Host to Centreon
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "host_testt"
        alias: "test"
        ipaddr: "127.0.0.1"
        hosttemplates:
          - name: App-DB-MySQL
          - name: HW-Printer-standard-rfc3805-custom
          - name: HW-UPS-Standard-Rfc1628-SNMP
            state: absent
        hostgroups:
          - name: hg_test
            state: absent
          - name: hg9
        #instance: Central
        status: enabled
        state: present
        params:
          - name: notes_url
            value: "https://wiki.company.org/servers/{{ ansible_fqdn }}"
          - name: notes
            value: "My Best server 2"
        macros:
          - name: "$_HOSTTEST$"
            value: value1_up
            is_password: 0
          - name: FOO
            value: bar
            description: description1
            state: absent
        #  - name: "$_HOSTSNMPCOMMUNITY$"
        #    value: "snmp_secret"
        #  - name: "$_HOSTTEST$"
        #    value: "supertest"
        #  - name: macropass
        #    value: mysecretpassword
        #    is_password: 1
        #    description: "shut..."
        applycfg: False
      delegate_to: localhost
  tags:
    - hosts


- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.138/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"

  tasks:
    - name: Add Host to Centreon
      centreon_hostgroup:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        hg:
         - name: "hg_ansible"
           alias: "test"
         - name: "hg_not_alias"
        state: absent
  tags:
    - hg

- hosts: localhost
  vars:
    centreon_url: "http://192.168.189.138/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "centreon"
  tasks:
    - name: Apply Config on poller
      centreon_poller:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        instance: "Central"
        action: "applycfg"
  tags:
    - poller